In [1]:
#230701348
#SUBRAMANIAN N
#II CSE F
#CS23334-Fundamentals of Data Science
import numpy as np

In [4]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a=a.reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a.ndim

2

In [9]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.mean(a)

np.float64(5.5)

In [11]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
a[:-1][1:4]

array([], shape=(0, 5), dtype=int64)

In [13]:
a[::-1][1:4]

array([[1, 2, 3, 4, 5]])

In [15]:
a[1:4][0]

array([ 6,  7,  8,  9, 10])

In [16]:
a[0,1:4]

array([2, 3, 4])

In [18]:
b=np.random.rand(1,11)
b

array([[0.71184919, 0.64574937, 0.96220141, 0.93406687, 0.0381356 ,
        0.85135803, 0.08477117, 0.35814221, 0.43047347, 0.17630793,
        0.64522589]])

In [19]:
b=np.random.randn(1,20)
b

array([[ 0.11248129, -0.04312709, -0.41856906,  1.63559871,  1.8880479 ,
         1.2543586 ,  1.33580074,  1.42306283,  0.57081589, -0.7820228 ,
        -1.29290083,  0.47833387,  0.41050911,  2.11950177, -0.09086552,
        -0.50988533,  0.27337768,  0.35243483,  0.49937481,  0.39676841]])

In [20]:
b=np.random.randint(1,100,size=10)
b

array([98, 59, 52, 20, 93, 86, 25, 91, 57, 92], dtype=int32)

In [21]:
b.mean()

np.float64(67.3)

In [22]:
np.mean(b)

np.float64(67.3)

In [23]:
b.sort()

In [24]:
b

array([20, 25, 52, 57, 59, 86, 91, 92, 93, 98], dtype=int32)

In [28]:
np.median(b)

np.float64(72.5)

In [29]:
b.dtype

dtype('int32')

In [33]:
c=np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
c*c.T

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])